=== throdoProudfoot/laugmtool/tests/testDataReferences/peuplesReferences.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/peuplesReferences.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE peuples SYSTEM "peuplesReferences.dtd">

    <peuples>
    ...
    </peuples>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT peuples (peuple)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT peuple (avantageCulturel|niveauDeVie|listeVocations|introduction|descriptionLongue|descriptionCourte|nom)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nom (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT descriptionCourte (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT descriptionLongue (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT introduction (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT listeVocations (vocation)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT vocation (#PCDATA)>
<!ATTLIST vocation
    categorie CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT niveauDeVie (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT avantageCulturel (#PCDATA)>

=== throdoProudfoot/laugmtool/dataReferences/peuplesReferences.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE peuples SYSTEM "peuplesReferences.dtd"> -->

<!-- To change this template, choose Tools | Templates and open the template 
	in the editor. -->

<peuples childNode="peuple">
	<peuple>
		<nom>Bardide</nom>
		<index>Bardide</index>
		<descriptionCourte>Humain citadin de Dale</descriptionCourte>
		<introduction>Là s'établit Dáin, qui devint Roi sous la Montagne, et,
			avec le temps, beaucoup d'autres Nains s'assemblèrent autour de son
			trône dans les anciennes salles.
		</introduction>
		<descriptionLongue>Quand les Nains s'établirent en Erebor, le Mont
			Solitaire, ils façonnèrent un royaume de pierre et de gemmes sous ses
			versants, au cours de longues et profondes excavations. Lampes et
			chandelles brûlèrent sans interruption pour éclairer leurs travaux,
			tandis que leur trésor gonflait au rythme de leur gloire en ces
			terres septentrionales.
		</descriptionLongue>
		<niveauDeVie>Riche</niveauDeVie>
		<avantageCulturel>Infatigable</avantageCulturel>
	</peuple>
	<peuple>
		<nom>Homme sauvage des bois</nom>
		<index>HommeSauvage</index>
		<descriptionCourte>Humain de Rosghobel </descriptionCourte>
		<introduction>Là s'établit Dáin, qui devint Roi sous la Montagne, et,
			avec le temps, beaucoup d'autres Nains s'assemblèrent autour de son
			trône dans les anciennes salles.
		</introduction>
		<descriptionLongue>Quand les Nains s'établirent en Erebor, le Mont
			Solitaire, ils façonnèrent un royaume de pierre et de gemmes sous ses
			versants, au cours de longues et profondes excavations. Lampes et
			chandelles brûlèrent sans interruption pour éclairer leurs travaux,
			tandis que leur trésor gonflait au rythme de leur gloire en ces
			terres septentrionales.
		</descriptionLongue>
		<niveauDeVie>Riche</niveauDeVie>
		<avantageCulturel>Infatigable</avantageCulturel>
	</peuple>
	<peuple>
		<nom>Béornide</nom>
		<index>Beornide</index>
		<descriptionCourte>Peuple de Béorn le changeur de forme
		</descriptionCourte>
		<introduction>Là s'établit Dáin, qui devint Roi sous la Montagne, et,
			avec le temps, beaucoup d'autres Nains s'assemblèrent autour de son
			trône dans les anciennes salles.
		</introduction>
		<descriptionLongue>Quand les Nains s'établirent en Erebor, le Mont
			Solitaire, ils façonnèrent un royaume de pierre et de gemmes sous ses
			versants, au cours de longues et profondes excavations. Lampes et
			chandelles brûlèrent sans interruption pour éclairer leurs travaux,
			tandis que leur trésor gonflait au rythme de leur gloire en ces
			terres septentrionales.
		</descriptionLongue>
		<niveauDeVie>Riche</niveauDeVie>
		<avantageCulturel>Infatigable</avantageCulturel>
	</peuple>
	<peuple>
		<nom>Elfe sylvains de sombre-Bois</nom>
		<index>ElfeSylvain</index>
		<descriptionCourte>Elfes sylvains du peuple de Thranduil
		</descriptionCourte>
		<introduction>Là s'établit Dáin, qui devint Roi sous la Montagne, et,
			avec le temps, beaucoup d'autres Nains s'assemblèrent autour de son
			trône dans les anciennes salles.
		</introduction>
		<descriptionLongue>Quand les Nains s'établirent en Erebor, le Mont
			Solitaire, ils façonnèrent un royaume de pierre et de gemmes sous ses
			versants, au cours de longues et profondes excavations. Lampes et
			chandelles brûlèrent sans interruption pour éclairer leurs travaux,
			tandis que leur trésor gonflait au rythme de leur gloire en ces
			terres septentrionales.
		</descriptionLongue>
		<niveauDeVie>Riche</niveauDeVie>
		<avantageCulturel>Infatigable</avantageCulturel>
	</peuple>
	<peuple>
		<nom>Hobbit de la Comté</nom>
		<index>Hobbit</index>
		<descriptionCourte>Petite-gens de la Comté</descriptionCourte>
		<introduction>Là s'établit Dáin, qui devint Roi sous la Montagne, et,
			avec le temps, beaucoup d'autres Nains s'assemblèrent autour de son
			trône dans les anciennes salles.
		</introduction>
		<descriptionLongue>Quand les Nains s'établirent en Erebor, le Mont
			Solitaire, ils façonnèrent un royaume de pierre et de gemmes sous ses
			versants, au cours de longues et profondes excavations. Lampes et
			chandelles brûlèrent sans interruption pour éclairer leurs travaux,
			tandis que leur trésor gonflait au rythme de leur gloire en ces
			terres septentrionales.
		</descriptionLongue>
		<niveauDeVie>Riche</niveauDeVie>
		<avantageCulturel>Infatigable</avantageCulturel>
	</peuple>
	<peuple>
		<nom>Nain du Mont-Solitaire</nom>
		<index>Nain</index>
		<descriptionCourte>Nain d'Erebor, peuple de Thorin Ecudechêne
		</descriptionCourte>
		<introduction>Là s'établit Dáin, qui devint Roi sous la Montagne, et,
			avec le temps, beaucoup d'autres Nains s'assemblèrent autour de son
			trône dans les anciennes salles.
		</introduction>
		<descriptionLongue>Quand les Nains s'établirent en Erebor, le Mont
			Solitaire, ils façonnèrent un royaume de pierre et de gemmes sous ses
			versants, au cours de longues et profondes excavations. Lampes et
			chandelles brûlèrent sans interruption pour éclairer leurs travaux,
			tandis que leur trésor gonflait au rythme de leur gloire en ces
			terres septentrionales.
		</descriptionLongue>
		<niveauDeVie>Riche</niveauDeVie>
		<avantageCulturel>Infatigable</avantageCulturel>
	</peuple>
</peuples>
